spring.application.name=firstproject
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:~/test_first
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.settings.web-allow-others=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:/data.sql
spring.sql.init.encoding=UTF-8