server:
  port: 8088

spring:
  application:
    name: board-login-img-security-oauth-react

  datasource:
    url: jdbc:mysql://localhost:3306/boardapp_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid

file:
  upload-dir: ./uploads

app:
  frontend-url: http://localhost:5173

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
